#!/bin/bash

## Dangerous! this operation does not allow normal users to bypass cattools!

AMD64_EFI_BIOS="https://github.com/miaoermua/CatWrt/releases/download/v23.8/CatWrt.v23.8.x86_64-squashfs-combined.img.gz"

sysupgrade -v $AMD64_EFI_BIOS
