#!/bin/bash

## Dangerous! this operation does not allow normal users to bypass cattools!

MT798X_SYSUP="https://github.com/miaoermua/CatWrt/releases/download/v23.8.mt798x/CatWrt.v23.8.mt798x-filogic-xiaomi_redmi-router-ax6000-squashfs-sysupgrade.bin"
GHPROXY="https://gh-proxy.com/"

sysupgrade -v $GHPROXY$MT798X_SYSUP
