#!/bin/bash

## Dangerous! this operation does not allow normal users to bypass cattools!

AMD64_EFI_SYSUP="https://github.com/miaoermua/CatWrt/releases/download/v24.9.mt7621/CatWrt.v24.9.mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin"
GHPROXY="https://mirror.ghproxy.com/"

sysupgrade -v $GHPROXY$MT7621_SYSUP
