#!/bin/bash

## Dangerous! this operation does not allow normal users to bypass cattools!

MT7621_SYSUP="https://github.com/miaoermua/CatWrt/releases/download/v24.9.mt7621/CatWrt.v24.9.mt7621-xiaomi_redmi-router-ac2100-squashfs-sysupgrade.bin"

sysupgrade -v $MT7621_SYSUP
